version: "3.9"
name: pei
services:
  kc_db:
    container_name: kc_db
    image: "postgres:15.4"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: keycloak
      POSTGRES_HOST: kc_db
    networks:
      icc_net:
        ipv4_address: 192.168.10.10
    ports:
      - "5433:5432"

  keycloak:
    container_name: keycloak
    build:
      context: ./keycloak
      args:
        KEYCLOAK_VERSION: 22.0.0
    command: ['start', '--optimized']
    depends_on:
      - "kc_db"
    environment:
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_URL: jdbc:postgresql://kc_db/keycloak
      KC_HOSTNAME_ADMIN_URL: http://${PUBLIC_URL}:8180
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_METRICS_ENABLED: 'true'
      KC_LOG: console
      KC_HOSTNAME_URL: http://${PUBLIC_URL}:8180
      KC_PROXY: edge
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      icc_net:
        ipv4_address: 192.168.10.11   
  
  icc_gateway:
      image: djedou/icc_gateway:v_0.3.1
      container_name: icc_gateway
      networks:
        icc_net:
          ipv4_address: 192.168.10.12
      ports:
        - 4012:4012
      environment:
        - GatewayAddress=192.168.10.12:4012
        - UserClientAddress=192.168.10.13:4013
      depends_on:
        - kc_db
        - keycloak

  icc_users:
      image: djedou/icc_users:v_0.1.0
      container_name: icc_users
      networks:
        icc_net:
          ipv4_address: 192.168.10.13
      environment:
        - UserClientAddress=192.168.10.13:4013
        - KeycloakAddress=http://192.168.10.11:8080
        - DatabaseAddress=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@192.168.10.10:5432/keycloak
      depends_on:
        - kc_db
        - keycloak
  
networks:
  icc_net:
    ipam:
      driver: default
      config:
          - 
            subnet: "192.168.10.0/24"

volumes:
  postgres_data: